"""JSON validation utilities"""
import json
import re
from typing import Dict, Tuple, Optional, Set
try:
    from .base import ValidationResult
except ImportError:
    from base import ValidationResult


def extract_json_from_response(response_text: str) -> str:
    """Extract JSON from a response"""
    json_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', response_text, re.DOTALL)
    if json_match:
        return json_match.group(1)
    start_idx = response_text.find('{')
    end_idx = response_text.rfind('}')
    if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
        return response_text[start_idx:end_idx+1]
    return response_text


def extract_python_from_response(response_text: str) -> str:
    """Extract Python code from a response"""
    # Try matching a ```python ... ``` block
    python_match = re.search(r'```(?:python)?\s*(import bpy.*?)```', response_text, re.DOTALL)
    if python_match:
        return python_match.group(1).strip()

    # Try matching any ``` ... ``` block containing import bpy
    code_match = re.search(r'```\s*(import bpy.*?)```', response_text, re.DOTALL)
    if code_match:
        return code_match.group(1).strip()

    # If no code block, try to find code starting from import bpy
    if 'import bpy' in response_text:
        start_idx = response_text.find('import bpy')
        # Find the end of the code (next non-code text or end of file)
        return response_text[start_idx:].strip()
    
    return response_text


def validate_stage3_code(code: str) -> ValidationResult:
    """Validate Blender Python code generated by Stage3"""
    errors = []
    warnings = []

    # 1. Basic syntax check
    try:
        compile(code, '<string>', 'exec')
    except SyntaxError as e:
        errors.append(f"Python syntax error (line {e.lineno}): {e.msg}")
        return ValidationResult(is_valid=False, errors=errors, warnings=warnings)

    # 2. Required import check
    if 'import bpy' not in code:
        errors.append("Missing 'import bpy'")

    # 3. Required function check
    required_functions = ['clear_scene', 'create_material', 'create_box']
    for func in required_functions:
        if f'def {func}' not in code:
            warnings.append(f"Recommend defining '{func}' function")

    # 4. Main function check
    if 'def run_layout_engine' not in code and 'def main' not in code:
        warnings.append("Recommend defining a main function 'run_layout_engine' or 'main'")

    # 5. Entry point check
    if '__name__' not in code:
        warnings.append("Recommend adding an if __name__ == '__main__' entry point")

    # 6. Blender 4.0+ compatibility check
    if 'Principled BSDF' in code and '.get(' not in code:
        warnings.append("Recommend using .get() for Principled BSDF access for Blender 4.0+ compatibility")

    # 7. Scene cleanup check
    if 'clear_scene' in code or 'delete' in code or 'remove' in code:
        pass  # OK
    else:
        warnings.append("Recommend clearing the scene at the start")

    # 8. Check that basic elements are created
    basic_elements = {
        'floor': ['floor', 'Floor', 'FLOOR'],
        'wall': ['wall', 'Wall', 'WALL'],
    }

    for element, keywords in basic_elements.items():
        if not any(kw in code for kw in keywords):
            warnings.append(f"Code may be missing {element} creation")

    # 9. Check for Collections usage
    if 'collection' not in code.lower() and 'Collection' not in code:
        warnings.append("Recommend using Blender Collections to organize objects")

    # 10. Check object count (rough estimate)
    box_count = code.count('create_box') + code.count('primitive_cube_add')
    if box_count < 5:
        warnings.append(f"Only detected about {box_count} object creations; some objects may be missing")
    
    return ValidationResult(is_valid=len(errors) == 0, errors=errors, warnings=warnings)


def validate_json_parseable(json_str: str) -> Tuple[bool, Optional[Dict], Optional[str]]:
    """Validate JSON parseability"""
    try:
        data = json.loads(json_str)
        return True, data, None
    except json.JSONDecodeError as e:
        return False, None, f"JSON parse error: {str(e)}"


def validate_stage1_schema(data: Dict) -> ValidationResult:
    """Validate Stage1 Schema"""
    errors = []
    warnings = []

    # Check top-level fields
    if "decoupled_zones" not in data:
        errors.append("Missing required field: decoupled_zones")
    if "architectural_features" not in data:
        errors.append("Missing required field: architectural_features")

    for field in ["scene_scale_understanding", "input_summary"]:
        if field not in data:
            warnings.append(f"Missing recommended field: {field}")

    # Collect all object_id
    all_object_ids = set()

    # Check zones
    zones = data.get("decoupled_zones", [])
    if not isinstance(zones, list):
        errors.append("decoupled_zones must be an array")
    else:
        for i, zone in enumerate(zones):
            zone_id = zone.get("zone_id")
            if not zone_id:
                errors.append(f"zone[{i}] missing zone_id")
            elif not re.match(r'^zone_\d+$', zone_id):
                warnings.append(f"zone_id '{zone_id}' has invalid format")

            for field in ["zone_name", "primary_function", "visual_boundaries"]:
                if field not in zone:
                    warnings.append(f"zone[{i}] ({zone_id}) missing field: {field}")

            # Check objects
            objects = zone.get("object_hierarchy", [])
            if not isinstance(objects, list):
                errors.append(f"zone[{i}] object_hierarchy must be an array")
            else:
                for j, obj in enumerate(objects):
                    obj_id = obj.get("object_id")
                    if not obj_id:
                        errors.append(f"zone[{i}].object[{j}] missing object_id")
                    else:
                        all_object_ids.add(obj_id)
                        if not re.match(r'^obj_\d+$', obj_id):
                            warnings.append(f"object_id '{obj_id}' has invalid format")

                    category = obj.get("category")
                    if category and category not in ["major", "minor"]:
                        errors.append(f"object '{obj_id}' category invalid")

                    placement_type = obj.get("placement_type")
                    parent_object = obj.get("parent_object")

                    if placement_type == "floor":
                        if parent_object is not None:
                            errors.append(f"object '{obj_id}': parent_object must be null when floor")
                    elif placement_type == "surface":
                        if parent_object is None:
                            errors.append(f"object '{obj_id}': parent_object must not be null when surface")
                    elif placement_type == "wall":
                        valid_parents = ["wall:north", "wall:south", "wall:east", "wall:west", "wall:unknown"]
                        if parent_object not in valid_parents:
                            errors.append(f"object '{obj_id}': parent_object invalid when wall")
                    elif placement_type:
                        errors.append(f"object '{obj_id}' placement_type invalid")

    # Check surface references
    for zone in zones:
        for obj in zone.get("object_hierarchy", []):
            if obj.get("placement_type") == "surface":
                parent = obj.get("parent_object")
                if parent and parent not in all_object_ids:
                    parent_match = re.search(r'(obj_\d+)', str(parent))
                    if parent_match and parent_match.group(1) not in all_object_ids:
                        errors.append(f"object '{obj.get('object_id')}' parent_object reference does not exist")

    # Check features
    features = data.get("architectural_features", [])
    if not isinstance(features, list):
        errors.append("architectural_features must be an array")
    else:
        for i, feat in enumerate(features):
            feat_id = feat.get("feature_id")
            if not feat_id:
                warnings.append(f"feature[{i}] missing feature_id")
            elif not re.match(r'^feat_\d+$', feat_id):
                warnings.append(f"feature_id '{feat_id}' has invalid format")

    # Wall-mounted object recall check: most indoor scenes have at least wall art / mirrors / clocks etc.
    # Zero wall-mounted objects usually means recognition failure rather than truly empty walls.
    wall_mounted_count = 0
    floor_major_keywords = [
        "bed", "sofa", "couch", "desk", "dining table", "dressing table",
        "vanity", "console", "headboard", "tv stand", "media console",
        "workstation", "sink", "fireplace",
    ]
    has_wallart_magnet = False
    for zone in zones:
        for obj in zone.get("object_hierarchy", []):
            if obj.get("placement_type") == "wall":
                wall_mounted_count += 1
            name_l = (obj.get("name") or "").lower()
            cat = obj.get("category")
            if cat == "major" and any(kw in name_l for kw in floor_major_keywords):
                has_wallart_magnet = True

    if wall_mounted_count == 0:
        if has_wallart_magnet:
            warnings.append(
                "[!] WALL-OBJECT RECALL zero hits: room contains 'wall-art magnet' furniture such as bed/sofa/desk, "
                "but the count of placement_type='wall' objects is 0. Please re-scan the four image edge strips "
                "(top=north wall, bottom=south wall, left=west wall, right=east wall) for wall art/posters/mirrors/"
                "clocks/sconces/racks (see Step B.6). A row of N independent picture frames should produce N independent objects."
            )
        else:
            warnings.append(
                "[i] No placement_type='wall' objects in the current output. "
                "If the room walls really are empty this can be ignored; otherwise please redo the wall scan in Step B.6."
            )

    return ValidationResult(is_valid=len(errors) == 0, errors=errors, warnings=warnings)


def validate_stage2_schema(data: Dict) -> ValidationResult:
    """Validate Stage2 Scene Graph Schema"""
    errors = []
    warnings = []

    # Valid Zone relation types
    VALID_ZONE_RELATIONS = {
        "adjacent_to", "left_of", "right_of", "in_front_of", "behind",
        "inside", "part_of", "near"
    }
    VALID_DIRECTIONS = {"north", "south", "east", "west", None}

    # Predefined relation types
    VALID_RELATIONS = {
        # Spatial Position
        "adjacent_to", "near", "far_from", "between", "aligned_with",
        "parallel_to", "perpendicular_to", "centered_on",
        # Directional
        "facing", "facing_away", "in_front_of", "behind", "left_of",
        "right_of", "above", "below",
        # Support & Contact
        "on", "under", "hanging_from", "leaning_against", "attached_to",
        "mounted_on", "supported_by",
        # Containment
        "inside", "contained_in", "surrounding", "enclosed_by", "tucked_under",
        # Functional
        "used_with", "controls", "illuminates", "stores", "displays",
        "provides_seating_for", "works_on",
        # Grouping
        "part_of", "grouped_with", "matching", "set_of"
    }

    VALID_RELATION_CATEGORIES = {
        "spatial_position", "directional", "support", "containment",
        "functional", "grouping"
    }

    # Mapping from relation type to category
    RELATION_TO_CATEGORY = {
        "adjacent_to": "spatial_position", "near": "spatial_position", 
        "far_from": "spatial_position", "between": "spatial_position",
        "aligned_with": "spatial_position", "parallel_to": "spatial_position", 
        "perpendicular_to": "spatial_position", "centered_on": "spatial_position",
        
        "facing": "directional", "facing_away": "directional", 
        "in_front_of": "directional", "behind": "directional",
        "left_of": "directional", "right_of": "directional", 
        "above": "directional", "below": "directional",
        
        "on": "support", "under": "support", "hanging_from": "support", 
        "leaning_against": "support", "attached_to": "support", 
        "mounted_on": "support", "supported_by": "support",
        
        "inside": "containment", "contained_in": "containment", 
        "surrounding": "containment", "enclosed_by": "containment", 
        "tucked_under": "containment",
        
        "used_with": "functional", "controls": "functional", 
        "illuminates": "functional", "stores": "functional", 
        "displays": "functional", "provides_seating_for": "functional", 
        "works_on": "functional",
        
        "part_of": "grouping", "grouped_with": "grouping", 
        "matching": "grouping", "set_of": "grouping"
    }
    
    # Check top-level fields
    if "scene_graphs" not in data:
        errors.append("Missing required field: scene_graphs")
        return ValidationResult(is_valid=False, errors=errors, warnings=warnings)

    # Check zone_relations (recommended field)
    zone_relations = data.get("zone_relations", [])
    if not zone_relations:
        warnings.append("Missing zone_relations field; recommend adding spatial relations between zones")
    else:
        # Collect all zone_id
        all_zone_ids = {g.get("zone_id") for g in data.get("scene_graphs", []) if g.get("zone_id")}

        for i, zr in enumerate(zone_relations):
            # Check required fields
            for field in ["source", "target", "relation"]:
                if field not in zr:
                    errors.append(f"zone_relations[{i}] missing required field: {field}")

            source = zr.get("source")
            target = zr.get("target")
            relation = zr.get("relation")
            direction = zr.get("direction")

            # Check whether zone_id exists
            if source and source not in all_zone_ids:
                warnings.append(f"zone_relations[{i}] source '{source}' not in scene_graphs")
            if target and target not in all_zone_ids:
                warnings.append(f"zone_relations[{i}] target '{target}' not in scene_graphs")

            # Check relation type
            if relation and relation not in VALID_ZONE_RELATIONS:
                warnings.append(f"zone_relations[{i}] relation '{relation}' is not a recommended zone relation type")

            # Check direction
            if direction and direction not in VALID_DIRECTIONS:
                warnings.append(f"zone_relations[{i}] direction '{direction}' is not a valid direction")

    scene_graphs = data.get("scene_graphs", [])
    if not isinstance(scene_graphs, list):
        errors.append("scene_graphs must be an array")
        return ValidationResult(is_valid=False, errors=errors, warnings=warnings)

    if len(scene_graphs) == 0:
        warnings.append("scene_graphs is an empty array")

    # Check each scene graph
    for i, graph in enumerate(scene_graphs):
        zone_id = graph.get("zone_id")

        # Check required fields
        for field in ["zone_id", "zone_root", "nodes", "edges"]:
            if field not in graph:
                errors.append(f"scene_graphs[{i}] missing required field: {field}")

        # Recommended fields
        for field in ["zone_function", "anchor_object"]:
            if field not in graph:
                warnings.append(f"scene_graphs[{i}] ({zone_id}) missing recommended field: {field}")

        # Validate zone_id format
        if zone_id and not re.match(r'^zone_\d+$', zone_id):
            warnings.append(f"zone_id '{zone_id}' does not match recommended format 'zone_XX'")

        # Collect node ids
        node_ids = set()
        major_node_ids = set()
        minor_node_ids = set()

        nodes = graph.get("nodes", [])
        if not isinstance(nodes, list):
            errors.append(f"scene_graphs[{i}] ({zone_id}) nodes must be an array")
            continue

        # Check nodes
        for j, node in enumerate(nodes):
            node_id = node.get("id")
            if not node_id:
                errors.append(f"scene_graphs[{i}].nodes[{j}] missing id")
                continue

            node_ids.add(node_id)

            # Check required node fields
            for field in ["label", "type", "attributes"]:
                if field not in node:
                    errors.append(f"node '{node_id}' missing required field: {field}")

            # Check placement_type (important field)
            placement_type = node.get("placement_type")
            if placement_type:
                if placement_type not in ["floor", "surface", "wall"]:
                    errors.append(f"node '{node_id}' placement_type must be 'floor', 'surface' or 'wall'")
            else:
                warnings.append(f"node '{node_id}' missing placement_type field")

            # Check type
            node_type = node.get("type")
            if node_type not in ["Major", "Minor"]:
                errors.append(f"node '{node_id}' type must be 'Major' or 'Minor'")
            else:
                if node_type == "Major":
                    major_node_ids.add(node_id)
                else:
                    minor_node_ids.add(node_id)

            # Check attributes
            attributes = node.get("attributes", [])
            if not isinstance(attributes, list):
                errors.append(f"node '{node_id}' attributes must be an array")
            elif len(attributes) < 2:
                warnings.append(f"node '{node_id}' should have at least 2 attributes")
            elif len(attributes) > 5:
                warnings.append(f"node '{node_id}' has too many attributes (>{5})")

        # Check anchor_object
        anchor_object = graph.get("anchor_object")
        if anchor_object and anchor_object not in node_ids:
            errors.append(f"scene_graphs[{i}] ({zone_id}) anchor_object '{anchor_object}' not in nodes")
        if anchor_object and anchor_object not in major_node_ids:
            warnings.append(f"scene_graphs[{i}] ({zone_id}) anchor_object should be a Major-type node")

        # Check edges
        edges = graph.get("edges", [])
        if not isinstance(edges, list):
            errors.append(f"scene_graphs[{i}] ({zone_id}) edges must be an array")
            continue

        # Count relations per node
        node_relation_count = {nid: 0 for nid in node_ids}

        for k, edge in enumerate(edges):
            # Check required fields
            for field in ["source", "target", "relation"]:
                if field not in edge:
                    errors.append(f"scene_graphs[{i}].edges[{k}] missing required field: {field}")

            # Recommended fields
            for field in ["relation_category", "context"]:
                if field not in edge:
                    warnings.append(f"scene_graphs[{i}].edges[{k}] missing recommended field: {field}")

            source = edge.get("source")
            target = edge.get("target")
            relation = edge.get("relation")
            relation_category = edge.get("relation_category")

            # Check whether source and target exist
            if source and source not in node_ids and source != "zone_root":
                errors.append(f"edge[{k}] source '{source}' not in nodes")
            if target and target not in node_ids and target != "zone_root":
                errors.append(f"edge[{k}] target '{target}' not in nodes")

            # Count relations
            if source in node_relation_count:
                node_relation_count[source] += 1

            # Check relation validity
            if relation and relation not in VALID_RELATIONS:
                errors.append(f"edge[{k}] uses undefined relation: '{relation}'")

            # Check relation_category validity
            if relation_category and relation_category not in VALID_RELATION_CATEGORIES:
                errors.append(f"edge[{k}] relation_category '{relation_category}' is invalid")

            # Check relation and relation_category match
            if relation and relation_category:
                expected_category = RELATION_TO_CATEGORY.get(relation)
                if expected_category and expected_category != relation_category:
                    errors.append(
                        f"edge[{k}] relation '{relation}' does not match relation_category '{relation_category}', "
                        f"should be '{expected_category}'"
                    )

            # Check whether Minor nodes connect directly to zone_root
            if source in minor_node_ids and target == "zone_root":
                warnings.append(
                    f"edge[{k}] Minor node '{source}' connects directly to zone_root; "
                    f"recommend connecting to the parent Major node"
                )

        # Check relation completeness
        for node_id in major_node_ids:
            if node_relation_count[node_id] < 2:
                warnings.append(
                    f"scene_graphs[{i}] ({zone_id}) Major node '{node_id}' "
                    f"has only {node_relation_count[node_id]} relations; recommend at least 2-3"
                )

        for node_id in minor_node_ids:
            if node_relation_count[node_id] < 1:
                warnings.append(
                    f"scene_graphs[{i}] ({zone_id}) Minor node '{node_id}' "
                    f"has no relations; recommend at least 1 support/containment relation"
                )
    
    return ValidationResult(is_valid=len(errors) == 0, errors=errors, warnings=warnings)


def validate_stage2_object_centric_schema(
    data: Dict,
    stage1_json: Optional[Dict] = None,
) -> ValidationResult:
    """Validate Stage2 Object-Centric Dense Graph Schema.

    Args:
        data: stage2 output (final JSON after the runner has merged the skeleton).
        stage1_json: if provided, enable strict comparison (id sets / field consistency / relation count fallback).
                     Backwards compatible (stage1_json=None skips strict checks).
    """
    errors = []
    warnings = []

    required_top = ["meta", "nodes", "edges", "zone_graphs", "global_graph"]
    for field in required_top:
        if field not in data:
            errors.append(f"Missing required field: {field}")
    if errors:
        return ValidationResult(is_valid=False, errors=errors, warnings=warnings)

    # Validate meta
    meta = data.get("meta", {})
    for field in ["stage", "north_is", "notes"]:
        if field not in meta:
            warnings.append(f"meta missing field: {field}")

    # Validate nodes
    nodes = data.get("nodes", [])
    if not isinstance(nodes, list) or not nodes:
        errors.append("nodes must be a non-empty array")
        return ValidationResult(is_valid=False, errors=errors, warnings=warnings)

    node_ids = set()
    node_kind_map = {}
    zone_map = {}

    for i, node in enumerate(nodes):
        nid = node.get("id")
        if not nid:
            errors.append(f"nodes[{i}] missing id")
            continue
        if nid in node_ids:
            errors.append(f"nodes has duplicate id: {nid}")
        node_ids.add(nid)
        node_kind_map[nid] = node.get("node_kind", "object")
        zone_map[nid] = node.get("zone_id")

        for field in ["label", "zone_id", "type", "placement_type", "visual_attributes"]:
            if field not in node:
                errors.append(f"node '{nid}' missing required field: {field}")

        placement_type = node.get("placement_type")
        if placement_type and placement_type not in ["floor", "surface", "wall"]:
            errors.append(f"node '{nid}' placement_type invalid")

        node_kind = node.get("node_kind")
        if node_kind and node_kind not in ["object", "architecture"]:
            errors.append(f"node '{nid}' node_kind invalid")

    # Validate edges
    edges = data.get("edges", [])
    if not isinstance(edges, list) or not edges:
        errors.append("edges must be a non-empty array")
        return ValidationResult(is_valid=False, errors=errors, warnings=warnings)

    VALID_RELATIONS = {
        # position
        "north_of", "south_of", "east_of", "west_of",
        "north_east_of", "north_west_of", "south_east_of", "south_west_of",
        "overlapping", "partially_overlapping",
        # distance
        "touching", "adjacent_to", "near", "far_from", "separated_by_walkway",
        # alignment
        "aligned_left", "aligned_right", "aligned_top", "aligned_bottom",
        "aligned_center_x", "aligned_center_y", "in_same_row_as", "in_same_column_as",
        "parallel_to", "perpendicular_to", "centered_on",
        # support
        "on_top_of", "supports", "mounted_on", "under", "above",
        # containment
        "inside", "contains",
        # functional
        "faces_for_use", "used_with", "reachable_from", "blocks_access_to", "provides_clearance_for",
        # grouping
        "grouped_with", "part_of_set", "surrounds", "surrounded_by", "pairs_with",
        # architecture
        "against_wall", "near_wall", "aligned_with_wall", "next_to_door", "faces_opening", "along_window",
        # corner anchors (v3.1, 2026-05-02)
        "in_corner_NE", "in_corner_NW", "in_corner_SE", "in_corner_SW",
        "contains_corner_NE", "contains_corner_NW",
        "contains_corner_SE", "contains_corner_SW",
    }

    VALID_CATEGORIES = {
        "position", "distance", "alignment", "support", "containment", "functional", "grouping", "architecture"
    }
    VALID_SCOPES = {"intra_zone", "inter_zone", "object_to_architecture"}

    edge_ids = set()
    inverse_check = []

    for i, edge in enumerate(edges):
        eid = edge.get("edge_id")
        if not eid:
            errors.append(f"edges[{i}] missing edge_id")
            continue
        if eid in edge_ids:
            errors.append(f"edges has duplicate edge_id: {eid}")
        edge_ids.add(eid)

        for field in ["source", "target", "relation", "relation_category", "scope", "spatial_signature", "visual_reasoning"]:
            if field not in edge:
                errors.append(f"edges[{i}] missing required field: {field}")

        source = edge.get("source")
        target = edge.get("target")
        if source and source not in node_ids:
            errors.append(f"edges[{i}] source does not exist: {source}")
        if target and target not in node_ids:
            errors.append(f"edges[{i}] target does not exist: {target}")

        relation = edge.get("relation")
        if relation and relation not in VALID_RELATIONS:
            errors.append(f"edges[{i}] relation invalid: {relation}")

        category = edge.get("relation_category")
        if category and category not in VALID_CATEGORIES:
            errors.append(f"edges[{i}] relation_category invalid: {category}")

        scope = edge.get("scope")
        if scope and scope not in VALID_SCOPES:
            errors.append(f"edges[{i}] scope invalid: {scope}")

        spatial = edge.get("spatial_signature", {})
        # Note: distance field removed - it's unreliable and misleads Stage3
        for key in ["direction_8", "overlap", "alignment"]:
            if key not in spatial:
                errors.append(f"edges[{i}] spatial_signature missing field: {key}")

        # queue for inverse check (warning-level)
        if source and target and relation:
            inverse_check.append((source, target, relation))

    # Zone graphs
    zone_graphs = data.get("zone_graphs", [])
    if not isinstance(zone_graphs, list):
        errors.append("zone_graphs must be an array")
    else:
        for i, zg in enumerate(zone_graphs):
            for field in ["zone_id", "node_ids", "edge_ids"]:
                if field not in zg:
                    errors.append(f"zone_graphs[{i}] missing required field: {field}")
            node_ids_list = zg.get("node_ids", [])
            edge_ids_list = zg.get("edge_ids", [])
            for nid in node_ids_list:
                if nid not in node_ids:
                    errors.append(f"zone_graphs[{i}] node_id does not exist: {nid}")
            for eid in edge_ids_list:
                if eid not in edge_ids:
                    errors.append(f"zone_graphs[{i}] edge_id does not exist: {eid}")

    # Global graph
    global_graph = data.get("global_graph", {})
    if "node_ids" not in global_graph or "edge_ids" not in global_graph:
        errors.append("global_graph must contain node_ids and edge_ids")
    else:
        for nid in global_graph.get("node_ids", []):
            if nid not in node_ids:
                errors.append(f"global_graph node_id does not exist: {nid}")
        for eid in global_graph.get("edge_ids", []):
            if eid not in edge_ids:
                errors.append(f"global_graph edge_id does not exist: {eid}")

    # Inverse edge warnings (not hard error)
    inverse_map = {
        "north_of": "south_of",
        "south_of": "north_of",
        "east_of": "west_of",
        "west_of": "east_of",
        "north_east_of": "south_west_of",
        "south_west_of": "north_east_of",
        "north_west_of": "south_east_of",
        "south_east_of": "north_west_of",
        "overlapping": "overlapping",
        "partially_overlapping": "partially_overlapping",
        "touching": "touching",
        "adjacent_to": "adjacent_to",
        "near": "near",
        "far_from": "far_from",
        "separated_by_walkway": "separated_by_walkway",
        "aligned_left": "aligned_left",
        "aligned_right": "aligned_right",
        "aligned_top": "aligned_top",
        "aligned_bottom": "aligned_bottom",
        "aligned_center_x": "aligned_center_x",
        "aligned_center_y": "aligned_center_y",
        "in_same_row_as": "in_same_row_as",
        "in_same_column_as": "in_same_column_as",
        "parallel_to": "parallel_to",
        "perpendicular_to": "perpendicular_to",
        "centered_on": "centered_on",
        "on_top_of": "supports",
        "supports": "on_top_of",
        "inside": "contains",
        "contains": "inside",
        "under": "above",
        "above": "under",
        "used_with": "used_with",
        "grouped_with": "grouped_with",
        "part_of_set": "part_of_set",
        "surrounds": "surrounded_by",
        "surrounded_by": "surrounds",
        "pairs_with": "pairs_with",
        # v3.1: corner anchors
        "in_corner_NE": "contains_corner_NE",
        "contains_corner_NE": "in_corner_NE",
        "in_corner_NW": "contains_corner_NW",
        "contains_corner_NW": "in_corner_NW",
        "in_corner_SE": "contains_corner_SE",
        "contains_corner_SE": "in_corner_SE",
        "in_corner_SW": "contains_corner_SW",
        "contains_corner_SW": "in_corner_SW",
    }
    edge_triplets = {(e.get("source"), e.get("target"), e.get("relation")) for e in edges}
    for s, t, r in inverse_check:
        inv = inverse_map.get(r)
        if inv and (t, s, inv) not in edge_triplets:
            warnings.append(f"Missing inverse edge: {t} --({inv})--> {s}")

    # ============================================================
    # Strict comparison with stage1 (v3: main graph contains only major+architecture, minor goes to sidecar)
    # ============================================================
    if stage1_json is not None:
        expected_major_ids: Set[str] = set()
        expected_minor_ids: Set[str] = set()
        expected_arch_ids: Set[str] = set()
        stage1_meta: Dict[str, Dict[str, str]] = {}

        for zone in stage1_json.get("decoupled_zones", []) or []:
            zid = zone.get("zone_id")
            for obj in zone.get("object_hierarchy", []) or []:
                oid = obj.get("object_id")
                if not oid:
                    continue
                cat = (obj.get("category") or "minor").lower()
                if cat == "major":
                    expected_major_ids.add(oid)
                    stage1_meta[oid] = {
                        "zone_id": zid,
                        "placement_type": obj.get("placement_type") or "",
                        "type": "Major",
                    }
                else:
                    expected_minor_ids.add(oid)

        for feat in stage1_json.get("architectural_features", []) or []:
            fid = feat.get("feature_id")
            if not fid:
                continue
            ftype = (feat.get("feature_type") or "").lower()
            placement = "wall" if ftype in {"wall", "door", "window"} else "floor"
            expected_arch_ids.add(fid)
            stage1_meta[fid] = {
                "zone_id": "global",
                "placement_type": placement,
                "type": "Fixed",
            }

        # Main graph expected = major + architecture (minor must not appear)
        expected_main_ids = expected_major_ids | expected_arch_ids
        actual_ids = set(node_ids)

        # v3.1: 4 virtual corner anchors auto-injected by stage2, not in stage1
        # (corner_NE/NW/SE/SW); not counted as missing/extra.
        VIRTUAL_CORNER_IDS = {"corner_NE", "corner_NW", "corner_SE", "corner_SW"}

        missing = expected_main_ids - actual_ids
        if missing:
            sample = sorted(missing)[:10]
            extra_str = "..." if len(missing) > 10 else ""
            errors.append(
                f"nodes missing stage1 main-graph ids (major+arch, total {len(missing)}): "
                f"{sample}{extra_str}"
            )

        extra = actual_ids - expected_main_ids - VIRTUAL_CORNER_IDS
        if extra:
            # Distinguish: extras that are minor (warning, lenient per user choice) vs completely unknown (error)
            extra_minor = extra & expected_minor_ids
            extra_unknown = extra - expected_minor_ids
            if extra_minor:
                sample = sorted(extra_minor)[:10]
                extra_str = "..." if len(extra_minor) > 10 else ""
                warnings.append(
                    f"Main graph contains minor ids (should only appear in minor_objects sidecar, "
                    f"total {len(extra_minor)}): {sample}{extra_str}"
                )
            if extra_unknown:
                sample = sorted(extra_unknown)[:10]
                extra_str = "..." if len(extra_unknown) > 10 else ""
                errors.append(
                    f"nodes contain unknown non-stage1 ids (total {len(extra_unknown)}): "
                    f"{sample}{extra_str}"
                )

        # Field-by-field comparison (only for ids that should be in the main graph)
        mismatch_count = 0
        for n in nodes:
            nid = n.get("id")
            expect = stage1_meta.get(nid)
            if not expect:
                continue
            for field in ("zone_id", "placement_type", "type"):
                if n.get(field) != expect[field]:
                    mismatch_count += 1
                    if mismatch_count <= 10:
                        errors.append(
                            f"node '{nid}' {field} inconsistent: "
                            f"stage2='{n.get(field)}' vs stage1='{expect[field]}'"
                        )
        if mismatch_count > 10:
            errors.append(f"... and {mismatch_count - 10} more field inconsistencies (omitted)")

        # architecture id must start with feat_ or corner_ (v3.1: corner anchors)
        for n in nodes:
            if n.get("node_kind") == "architecture":
                nid = n.get("id", "")
                if not (nid.startswith("feat_") or nid.startswith("corner_")):
                    errors.append(
                        f"architecture node id must start with feat_ or corner_: '{nid}'"
                    )

        # Relation count fallback (warning, avoid infinite iteration). v3 no longer checks minor (already split off)
        edge_count: Dict[str, int] = {}
        for e in edges:
            for endpoint in (e.get("source"), e.get("target")):
                if endpoint:
                    edge_count[endpoint] = edge_count.get(endpoint, 0) + 1

        sparse_major = []
        for n in nodes:
            nid = n.get("id")
            t = n.get("type")
            cnt = edge_count.get(nid, 0)
            if t == "Major" and cnt < 6:
                sparse_major.append((nid, cnt))

        if sparse_major:
            sample = sparse_major[:5]
            warnings.append(
                f"Major nodes with relation count < 6 (total {len(sparse_major)}), e.g.: {sample}"
            )

        # ============================================================
        # v3 added: validate minor_objects sidecar completeness
        # ============================================================
        sidecar = data.get("minor_objects")
        if sidecar is None:
            errors.append("Missing minor_objects sidecar field (required in v3)")
        else:
            if not isinstance(sidecar, list):
                errors.append("minor_objects must be an array")
            else:
                sidecar_ids: Set[str] = set()
                for i, m in enumerate(sidecar):
                    if not isinstance(m, dict):
                        errors.append(f"minor_objects[{i}] is not an object")
                        continue
                    mid = m.get("id")
                    if not mid:
                        errors.append(f"minor_objects[{i}] missing id")
                        continue
                    if mid in sidecar_ids:
                        errors.append(f"minor_objects has duplicate id: {mid}")
                    sidecar_ids.add(mid)
                    for field in ("label", "zone_id", "placement_type"):
                        if field not in m:
                            errors.append(
                                f"minor_objects[{i}] (id={mid}) missing field: {field}"
                            )

                missing_minor = expected_minor_ids - sidecar_ids
                if missing_minor:
                    sample = sorted(missing_minor)[:10]
                    extra_str = "..." if len(missing_minor) > 10 else ""
                    errors.append(
                        f"minor_objects sidecar missing stage1 minor ids "
                        f"(total {len(missing_minor)}): {sample}{extra_str}"
                    )

                extra_minor_sidecar = sidecar_ids - expected_minor_ids
                if extra_minor_sidecar:
                    sample = sorted(extra_minor_sidecar)[:10]
                    extra_str = "..." if len(extra_minor_sidecar) > 10 else ""
                    warnings.append(
                        f"minor_objects sidecar contains extra ids "
                        f"(total {len(extra_minor_sidecar)}): {sample}{extra_str}"
                    )

    return ValidationResult(is_valid=len(errors) == 0, errors=errors, warnings=warnings)


