"""
IncrementalLayoutEngine template (for prompts)

Notes:
- This file provides reusable engine support for incremental placement, XY collision avoidance, and grid quantization.
- To make this safe to paste directly into prompts as a target template, it should not contain executable scene-specific examples.

Usage in the final Blender script generated by the LLM:
1) Recommended import:
   from IncrementalLayoutEngine import (
       IncrementalLayoutEngine,
       clear_scene,
       create_material,
       quantize,
       quantize_ceil,
   )
2) Implement your own run_layout_engine() in the final script:
   - Place floors, walls, and partitions first (floor collidable_xy=False).
   - Then place collidable furniture in order, one add_furniture call at a time.
   - Finally attach decorations to the final parent-object positions from attachments (add_decoration).
"""

import bpy
import math

# Grid quantization unit: 10 cm = 0.1 m
GRID_SIZE = 0.1

def quantize(value):
    """Quantize a value to the nearest grid unit (0.1 m)"""
    return round(value / GRID_SIZE) * GRID_SIZE

def quantize_ceil(value):
    """Quantize a size upward to the grid to avoid shrinkage causing intersections or wall-thickness misclassification"""
    if value <= 0:
        return 0.0
    return math.ceil(value / GRID_SIZE) * GRID_SIZE

def quantize_vec3(vec):
    """Quantize a 3D vector to the grid, only on XY"""
    return (quantize(vec[0]), quantize(vec[1]), vec[2])

def quantize_size(size):
    """Quantize size to the grid, only on XY"""
    # Round dimensions upward: e.g. 0.15 m wall thickness -> 0.2 m, which better reflects occupied space
    return (quantize_ceil(size[0]), quantize_ceil(size[1]), size[2])

def quantize_size_decoration(size):
    """Decoration size quantization with better fidelity:
    - Quantize XY only when it is at least one grid unit, so a 0.02 m frame thickness is not inflated to 0.1 m
    - Keep XY values smaller than one grid unit unchanged for thin objects such as wall art, mirrors, and curtains
    """
    sx = quantize(size[0]) if abs(size[0]) >= GRID_SIZE else size[0]
    sy = quantize(size[1]) if abs(size[1]) >= GRID_SIZE else size[1]
    return (sx, sy, size[2])

def get_bbox_2d(location, size, rotation_z=0):
    """Get the object's 2D bounding box on the XY plane"""
    if abs(rotation_z) < 0.01:
        hx, hy = size[0] / 2, size[1] / 2
        return {
            'min_x': location[0] - hx,
            'max_x': location[0] + hx,
            'min_y': location[1] - hy,
            'max_y': location[1] + hy
        }
    else:
        hx, hy = size[0] / 2, size[1] / 2
        cos_a = math.cos(rotation_z)
        sin_a = math.sin(rotation_z)
        
        corners = [(-hx, -hy), (hx, -hy), (hx, hy), (-hx, hy)]
        rotated = []
        for cx, cy in corners:
            rx = cx * cos_a - cy * sin_a + location[0]
            ry = cx * sin_a + cy * cos_a + location[1]
            rotated.append((rx, ry))
        
        xs = [p[0] for p in rotated]
        ys = [p[1] for p in rotated]
        return {
            'min_x': min(xs),
            'max_x': max(xs),
            'min_y': min(ys),
            'max_y': max(ys)
        }

def check_overlap(bbox1, bbox2):
    """Check whether two bounding boxes overlap"""
    # Strict check: return True for any overlap
    return not (bbox1['max_x'] <= bbox2['min_x'] or 
                bbox1['min_x'] >= bbox2['max_x'] or
                bbox1['max_y'] <= bbox2['min_y'] or 
                bbox1['min_y'] >= bbox2['max_y'])

def clear_scene():
    """Clear the scene"""
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()
    for collection in bpy.data.collections:
        bpy.data.collections.remove(collection)

def create_material(name, color):
    """Create a material"""
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    bsdf = nodes.get("Principled BSDF")
    if bsdf:
        bsdf.inputs['Base Color'].default_value = color
    mat.diffuse_color = color
    return mat

def create_box(name, location, size, rotation=(0, 0, 0), material=None, collection=None):
    """Create a box"""
    bpy.ops.mesh.primitive_cube_add(size=1, location=location, rotation=rotation)
    obj = bpy.context.active_object
    obj.name = name
    obj.scale = size
    if material:
        obj.data.materials.append(material)
    if collection:
        collection.objects.link(obj)
        if obj.name in bpy.context.scene.collection.objects:
            bpy.context.scene.collection.objects.unlink(obj)
    return obj

def create_cylinder(name, location, size, rotation=(0, 0, 0), material=None, collection=None):
    """Create a cylinder
    
    Args:
        name: Object name
        location: Center position (x, y, z)
        size: Dimensions (diameter x, diameter y, height z); x and y are usually equal
        rotation: Rotation angles in radians
        material: Material
        collection: Blender collection
    """
    bpy.ops.mesh.primitive_cylinder_add(radius=1, depth=1, location=location, rotation=rotation)
    obj = bpy.context.active_object
    obj.name = name
    # Cylinder scale: x and y are radii, z is height
    obj.scale = (size[0] / 2, size[1] / 2, size[2])
    if material:
        obj.data.materials.append(material)
    if collection:
        collection.objects.link(obj)
        if obj.name in bpy.context.scene.collection.objects:
            bpy.context.scene.collection.objects.unlink(obj)
    return obj

def create_object(name, location, size, rotation=(0, 0, 0), material=None, collection=None, shape="box"):
    """Create an object according to shape type"""
    if shape == "cylinder":
        return create_cylinder(name, location, size, rotation, material, collection)
    else:
        return create_box(name, location, size, rotation, material, collection)

class IncrementalLayoutEngine:
    """Incremental layout engine: add objects one by one and optimize immediately"""
    
    def __init__(self, scene_w, scene_d, wall_thickness):
        self.scene_w = scene_w
        self.scene_d = scene_d
        self.wall_thickness = wall_thickness
        # All placed objects, used only for records
        self.placed_objects = []
        # Objects participating in XY collision: walls, partitions, and furniture. Floor should not participate in XY collision
        self.collision_objects = []
        
    def check_collision_with_placed(self, location, size, rotation_z):
        """Check whether an object at the given position overlaps placed objects"""
        new_bbox = get_bbox_2d(location, size, rotation_z)
        
        for placed in self.collision_objects:
            placed_bbox = get_bbox_2d(placed['location'], placed['size'], placed['rotation'][2])
            if check_overlap(new_bbox, placed_bbox):
                return True, placed['name']
        
        return False, None
    
    def _get_placed_object(self, name):
        """Get placed-object information by name"""
        for placed in self.collision_objects:
            if placed['name'] == name:
                return placed
        return None
    
    def _get_object_group(self, obj_name):
        """Identify the group an object belongs to
        
        Return the names of all objects in the group, including itself
        If the object does not belong to any group, return a list containing only itself
        """
        # Define object groups using name-prefix matching
        group_prefixes = {
            "Kitchen": ["Kitchen_Base", "Kitchen_Upper", "Kitchen_Jar", "Sink", "Coffee_Machine"],
            # More groups can be added, for example:
            # "Desk": ["Desk_Main", "Desk_Return", "Desk_Lamp"],
        }
        
        # Find the matching group
        for group_name, prefixes in group_prefixes.items():
            for prefix in prefixes:
                if prefix in obj_name:
                    # Found a matching group; return all objects in that group
                    group_members = []
                    for placed in self.collision_objects:
                        for p in prefixes:
                            if p in placed['name']:
                                group_members.append(placed['name'])
                    return group_members
        
        # Does not belong to any group
        return [obj_name]
    
    def _try_move_group_along_wall(self, group_members, away_from_loc, parallel_axis):
        """Try moving the entire object group along the wall
        
        Args:
            group_members: List of object names in the group
            away_from_loc: Position to move away from
            parallel_axis: "x" or "y", the axis for movement along the wall
        
        Returns:
            bool: Whether the move succeeded
        """
        if not group_members:
            return False
        
        # Get all objects in the group
        # During group movement, even objects with movable_xy=False should move, such as wall-mounted Kitchen_Upper
        group_objects = []
        for name in group_members:
            obj = self._get_placed_object(name)
            if obj:
                # For group movement, allow all objects to move, including movable_xy=False objects
                # They must preserve relative positions as part of the group
                group_objects.append(obj)
        
        if not group_objects:
            return False
        
        # Decide movement direction: away from the colliding object
        # Use the first object in the group as the reference
        ref_obj = group_objects[0]
        ref_loc = ref_obj['location']
        
        if parallel_axis == "x":
            if away_from_loc[0] > ref_loc[0]:
                directions = [-1]  # Colliding object is on the right; move left
            else:
                directions = [1]   # Colliding object is on the left; move right
        else:
            if away_from_loc[1] > ref_loc[1]:
                directions = [-1]
            else:
                directions = [1]
        
        max_search = (self.scene_w if parallel_axis == "x" else self.scene_d) / 2
        
        for direction in directions:
            for steps in range(1, int(max_search / GRID_SIZE)):
                offset = steps * GRID_SIZE * direction
                
                # Try moving the entire group
                new_locations = {}
                can_move = True
                
                # First compute new positions for all objects
                for obj in group_objects:
                    old_loc = obj['location']
                    
                    if parallel_axis == "x":
                        new_x = quantize(old_loc[0] + offset)
                        new_y = old_loc[1]
                    else:
                        new_x = old_loc[0]
                        new_y = quantize(old_loc[1] + offset)
                    
                    new_loc = (new_x, new_y, old_loc[2])
                    
                    # Check whether the new position is inside the scene
                    bbox = get_bbox_2d(new_loc, obj['size'], obj['rotation'][2])
                    if not self.is_within_scene(bbox):
                        can_move = False
                        break
                    
                    new_locations[obj['name']] = new_loc
                
                if not can_move:
                    break
                
                # Temporarily remove all objects in the group and test new positions for collision
                temp_removed = {}
                for obj in group_objects:
                    for i, placed in enumerate(self.collision_objects):
                        if placed['name'] == obj['name']:
                            temp_removed[obj['name']] = (i, self.collision_objects.pop(i))
                            break
                
                # Check whether the new positions of all group objects collide
                all_valid = True
                for obj in group_objects:
                    new_loc = new_locations[obj['name']]
                    collision, _ = self.check_collision_with_placed(
                        new_loc, obj['size'], obj['rotation'][2]
                    )
                    if collision:
                        all_valid = False
                        break
                
                if all_valid:
                    # All new positions are valid; update every object in the group
                    for obj in group_objects:
                        name = obj['name']
                        if name in temp_removed:
                            idx, old_obj = temp_removed[name]
                            old_obj['location'] = new_locations[name]
                            self.collision_objects.insert(idx, old_obj)
                    
                    dir_name = "left" if (parallel_axis == "x" and direction < 0) else \
                               "right" if (parallel_axis == "x" and direction > 0) else \
                               "front" if (parallel_axis == "y" and direction < 0) else "back"
                    group_name = group_members[0].split('_')[0] if group_members else "group"
                    print(f"      ✓ Moved {group_name} group ({len(group_members)} objects) along the wall toward {dir_name} by {abs(offset):.2f}m")
                    return True
                else:
                    # Restore objects
                    for name, (idx, old_obj) in temp_removed.items():
                        self.collision_objects.insert(idx, old_obj)
        
        return False
    
    def _try_move_placed_object_along_wall(self, placed_name, away_from_loc):
        """Try moving an already placed wall-adjacent object along the wall, away from the given position
        
        Args:
            placed_name: Name of the placed object
            away_from_loc: Position to move away from
            
        Returns:
            bool: Whether the move succeeded
        """
        placed = self._get_placed_object(placed_name)
        if not placed:
            return False
        
        # Check whether the object is movable
        if not placed.get('movable_xy', True):
            print(f"      {placed_name} is not movable")
            return False
        
        placed_loc = placed['location']
        placed_size = placed['size']
        rotation_z = placed['rotation'][2]
        
        # Check whether it is wall-adjacent
        wall_name, parallel_axis, _ = self._detect_wall_adjacency(placed_loc, placed_size)
        if not wall_name:
            return False
        
        # Decide movement direction: away from the colliding object
        if parallel_axis == "x":
            # Move along the X axis; decide whether to move left or right
            if away_from_loc[0] > placed_loc[0]:
                directions = [-1]  # Colliding object is on the right; move left
            else:
                directions = [1]   # Colliding object is on the left; move right
        else:
            # Move along the Y axis
            if away_from_loc[1] > placed_loc[1]:
                directions = [-1]  # Colliding object is in front; move backward
            else:
                directions = [1]   # Colliding object is behind; move forward
        
        max_search = (self.scene_w if parallel_axis == "x" else self.scene_d) / 2
        
        for direction in directions:
            for steps in range(1, int(max_search / GRID_SIZE)):
                offset = steps * GRID_SIZE * direction
                
                if parallel_axis == "x":
                    new_x = quantize(placed_loc[0] + offset)
                    new_y = placed_loc[1]
                else:
                    new_x = placed_loc[0]
                    new_y = quantize(placed_loc[1] + offset)
                
                new_loc = (new_x, new_y, placed_loc[2])
                
                # Check whether it is inside the scene
                bbox = get_bbox_2d(new_loc, placed_size, rotation_z)
                if not self.is_within_scene(bbox):
                    break
                
                # Temporarily remove this object from the collision list and check the new position
                old_idx = None
                for i, obj in enumerate(self.collision_objects):
                    if obj['name'] == placed_name:
                        old_idx = i
                        break
                
                if old_idx is not None:
                    temp_removed = self.collision_objects.pop(old_idx)
                    collision, _ = self.check_collision_with_placed(new_loc, placed_size, rotation_z)
                    
                    if not collision:
                        # Found a new position; update object position
                        temp_removed['location'] = new_loc
                        self.collision_objects.insert(old_idx, temp_removed)
                        
                        dir_name = "left" if (parallel_axis == "x" and direction < 0) else \
                                   "right" if (parallel_axis == "x" and direction > 0) else \
                                   "front" if (parallel_axis == "y" and direction < 0) else "back"
                        print(f"      ✓ Moved {placed_name} along the {wall_name} wall toward {dir_name} by {abs(offset):.2f}m to ({new_x:.2f}, {new_y:.2f})")
                        return True
                    else:
                        # Restore objects
                        self.collision_objects.insert(old_idx, temp_removed)
        
        return False
    
    def is_within_scene(self, bbox):
        """Check whether the bounding box is inside the scene bounds and does not cross the outer wall boundary
        
        Note: this is only a coarse bounds check used to quickly reject positions that are clearly outside the scene.
        Actual wall collision detection is handled by collision_objects, including outer walls and interior partitions.
        """
        # Use the scene outer boundary, outside the walls, rather than the inner boundary
        # This lets collision detection handle wall collisions instead of rejecting positions too early here
        half_w = self.scene_w / 2
        half_d = self.scene_d / 2
        
        return (bbox['min_x'] >= -half_w and 
                bbox['max_x'] <= half_w and
                bbox['min_y'] >= -half_d and 
                bbox['max_y'] <= half_d)
    
    def _detect_wall_adjacency(self, loc, size):
        """Detect whether an object is adjacent to a wall, returning the nearby wall and the parallel movement direction
        
        Returns:
            (wall_name, parallel_axis, parallel_directions)
            - wall_name: "north", "south", "east", "west", or None
            - parallel_axis: "x" or "y", the axis for movement along the wall
            - parallel_directions: [1, -1] or [-1, 1], preferred movement directions
        """
        half_w = self.scene_w / 2
        half_d = self.scene_d / 2
        wall_threshold = 0.5  # Treat objects within 0.5 m of a wall as wall-adjacent
        
        x, y = loc[0], loc[1]
        half_size_x = size[0] / 2
        half_size_y = size[1] / 2
        
        # Check north wall (y = +half_d)
        if y + half_size_y > half_d - wall_threshold:
            # Adjacent to north wall; move along X, preferring left (negative direction)
            return "north", "x", [-1, 1]
        
        # Check south wall (y = -half_d)
        if y - half_size_y < -half_d + wall_threshold:
            # Adjacent to south wall; move along X
            return "south", "x", [-1, 1]
        
        # Check east wall (x = +half_w)
        if x + half_size_x > half_w - wall_threshold:
            # Adjacent to east wall; move along Y
            return "east", "y", [-1, 1]
        
        # Check west wall (x = -half_w)
        if x - half_size_x < -half_w + wall_threshold:
            # Adjacent to west wall; move along Y
            return "west", "y", [-1, 1]
        
        return None, None, None
    
    def _search_along_wall(self, initial_loc, size, rotation_z, parallel_axis, directions, name):
        """Search for a valid position along the wall
        
        Args:
            parallel_axis: "x" or "y"
            directions: Search direction list, e.g. [-1, 1]
        
        Returns:
            (new_loc, found) - new position and whether one was found
        """
        max_search = (self.scene_w if parallel_axis == "x" else self.scene_d) / 2
        
        for direction in directions:
            for steps in range(1, int(max_search / GRID_SIZE)):
                offset = steps * GRID_SIZE * direction
                
                if parallel_axis == "x":
                    new_x = quantize(initial_loc[0] + offset)
                    new_y = initial_loc[1]
                else:
                    new_x = initial_loc[0]
                    new_y = quantize(initial_loc[1] + offset)
                
                new_loc = (new_x, new_y, initial_loc[2])
                
                # Check whether it is inside the scene
                bbox = get_bbox_2d(new_loc, size, rotation_z)
                if not self.is_within_scene(bbox):
                    break  # Outside the boundary; switch direction
                
                # Check collision
                collision, _ = self.check_collision_with_placed(new_loc, size, rotation_z)
                if not collision:
                    dist = abs(offset)
                    dir_name = "left" if (parallel_axis == "x" and direction < 0) else \
                               "right" if (parallel_axis == "x" and direction > 0) else \
                               "front" if (parallel_axis == "y" and direction < 0) else "back"
                    print(f"    → Moved along the wall toward {dir_name} by {dist:.2f}m to ({new_x:.2f}, {new_y:.2f})")
                    return new_loc, True
        
        return initial_loc, False
    
    def find_valid_position(self, initial_loc, size, rotation_z, name):
        """Find a non-overlapping position for an object, returning (location, size, used_original)
        
        Optimization strategy:
        1. Try the original position first
        2. If the colliding object is wall-adjacent, try moving it along the wall
        3. If the current object is wall-adjacent, try moving it along the wall
        4. Use spiral search only as the final fallback
        """
        # Try the original position first
        collision, colliding = self.check_collision_with_placed(initial_loc, size, rotation_z)
        
        if not collision:
            bbox = get_bbox_2d(initial_loc, size, rotation_z)
            if self.is_within_scene(bbox):
                return initial_loc, size, True
            else:
                print(f"  {name}: original position is outside the scene bounds")
        else:
            print(f"  {name}: original position overlaps {colliding}")
            
            # === Priority strategy: try moving the group containing the colliding object ===
            colliding_obj = self._get_placed_object(colliding)
            if colliding_obj:
                colliding_loc = colliding_obj['location']
                colliding_size = colliding_obj['size']
                
                # Check whether the colliding object is wall-adjacent
                coll_wall, parallel_axis, _ = self._detect_wall_adjacency(colliding_loc, colliding_size)
                
                if coll_wall:
                    # Get the group containing the colliding object
                    group_members = self._get_object_group(colliding)
                    
                    # If the colliding object belongs to a group with more than one object, try moving the whole group
                    if len(group_members) > 1:
                        print(f"    Detected {colliding} as part of an object group ({len(group_members)} objects); trying to move the whole group along the wall...")
                        moved = self._try_move_group_along_wall(group_members, initial_loc, parallel_axis)
                        
                        if moved:
                            # Recheck the original position
                            collision2, _ = self.check_collision_with_placed(initial_loc, size, rotation_z)
                            if not collision2:
                                print(f"    ✓ {name} can use the original position")
                                return initial_loc, size, True
                    
                    # If group movement failed or this is not a group, try moving a single object
                    my_volume = size[0] * size[1]
                    their_volume = colliding_size[0] * colliding_size[1]
                    
                    # If the colliding object is larger or similar in size, try moving it along the wall
                    if their_volume >= my_volume * 0.5:
                        print(f"    Trying to move wall-adjacent object {colliding} along the wall to free space...")
                        moved = self._try_move_placed_object_along_wall(colliding, initial_loc)
                        
                        if moved:
                            # Recheck the original position
                            collision2, _ = self.check_collision_with_placed(initial_loc, size, rotation_z)
                            if not collision2:
                                print(f"    ✓ {name} can use the original position")
                                return initial_loc, size, True
        
        # === If the current object is wall-adjacent, try moving along the wall ===
        wall_name, parallel_axis, directions = self._detect_wall_adjacency(initial_loc, size)
        
        if wall_name:
            print(f"    Detected proximity to the {wall_name} wall; searching along the wall first...")
            new_loc, found = self._search_along_wall(
                initial_loc, size, rotation_z, parallel_axis, directions, name
            )
            if found:
                return new_loc, size, False
            print(f"    Wall-parallel search could not resolve the collision; trying spiral search...")
        
        # === Spiral search for a new position ===
        max_search = min(self.scene_w, self.scene_d) / 2
        
        for radius_steps in range(1, int(max_search / GRID_SIZE)):
            radius = radius_steps * GRID_SIZE
            num_angles = max(16, int(radius / GRID_SIZE * 8))
            
            for angle_idx in range(num_angles):
                angle = 2 * math.pi * angle_idx / num_angles
                
                new_x = quantize(initial_loc[0] + radius * math.cos(angle))
                new_y = quantize(initial_loc[1] + radius * math.sin(angle))
                new_loc = (new_x, new_y, initial_loc[2])
                
                # Check whether it is inside the scene
                bbox = get_bbox_2d(new_loc, size, rotation_z)
                if not self.is_within_scene(bbox):
                    continue
                
                # Check collision
                collision, _ = self.check_collision_with_placed(new_loc, size, rotation_z)
                if not collision:
                    dist = math.sqrt((new_x - initial_loc[0])**2 + (new_y - initial_loc[1])**2)
                    print(f"    → Found new position ({new_x:.2f}, {new_y:.2f}), {dist:.2f}m from original")
                    return new_loc, size, False
        
        # Movement could not resolve the collision; try resizing
        print(f"    ⚠ {name}: movement could not resolve the collision; trying to shrink size...")
        resized_loc, resized_size = self._try_resize_to_fit(initial_loc, size, rotation_z, name)
        if resized_size != size:
            return resized_loc, resized_size, False
        
        print(f"    ✗ Warning: could not find a non-overlapping position and could not shrink the object!")
        return initial_loc, size, False
    
    def _try_resize_to_fit(self, location, size, rotation_z, name):
        """Try shrinking object size to avoid collision, returning (new_location, new_size)"""
        min_scale = 0.5  # Minimum scale, no smaller than 50% of original size
        scale_step = 0.1  # Shrink by 10% each step
        
        original_size = size
        current_scale = 1.0
        
        while current_scale >= min_scale:
            current_scale -= scale_step
            # Shrink XY dimensions while keeping Z unchanged
            new_size = (
                quantize_ceil(original_size[0] * current_scale),
                quantize_ceil(original_size[1] * current_scale),
                original_size[2]
            )
            
            # Ensure dimensions are not smaller than the minimum grid unit
            if new_size[0] < GRID_SIZE or new_size[1] < GRID_SIZE:
                break
            
            # Check whether the original position works first
            collision, _ = self.check_collision_with_placed(location, new_size, rotation_z)
            bbox = get_bbox_2d(location, new_size, rotation_z)
            
            if not collision and self.is_within_scene(bbox):
                print(f"    → Shrunk to {current_scale:.0%}: ({new_size[0]:.2f}, {new_size[1]:.2f})")
                return location, new_size
            
            # If the original position does not work, run a small-range spiral search
            for radius_steps in range(1, 10):  # Smaller range
                radius = radius_steps * GRID_SIZE
                for angle_idx in range(16):
                    angle = 2 * math.pi * angle_idx / 16
                    new_x = quantize(location[0] + radius * math.cos(angle))
                    new_y = quantize(location[1] + radius * math.sin(angle))
                    new_loc = (new_x, new_y, location[2])
                    
                    bbox = get_bbox_2d(new_loc, new_size, rotation_z)
                    if not self.is_within_scene(bbox):
                        continue
                    
                    collision, _ = self.check_collision_with_placed(new_loc, new_size, rotation_z)
                    if not collision:
                        print(f"    → Shrunk to {current_scale:.0%} + moved: ({new_loc[0]:.2f}, {new_loc[1]:.2f})")
                        return new_loc, new_size
        
        # Could not shrink to a suitable size
        return location, size
    
    def add_fixed_object(self, name, location, size, rotation, material, collection, *, collidable_xy=True, shape="box"):
        """Add a fixed object such as a wall or floor; place directly without collision checks

        - collidable_xy=True: treat as an XY collision obstacle (wall or partition)
        - collidable_xy=False: do not participate in XY collision (Floor)
        - shape: "box" or "cylinder"
        """
        q_loc = quantize_vec3(location)
        q_size = quantize_size(size)
        
        # Create Blender object
        create_object(name, q_loc, q_size, rotation, material, collection, shape)
        
        record = {
            'name': name,
            'location': q_loc,
            'size': q_size,
            'rotation': rotation
        }
        # Add to record list
        self.placed_objects.append(record)
        # Add to collision list if needed
        if collidable_xy:
            self.collision_objects.append(record)
        
        flag = "collider" if collidable_xy else "non-collider"
        print(f"  {name}: fixed position ({q_loc[0]:.2f}, {q_loc[1]:.2f}) [{flag}]")
    
    def add_furniture(self, name, location, size, rotation, material, collection, *, shape="box"):
        """Add furniture: check collisions, optimize position, and shrink size if needed
        
        Args:
            shape: "box" or "cylinder"
        """
        q_size = quantize_size(size)
        q_initial_loc = quantize_vec3(location)
        rotation_z = rotation[2] if len(rotation) > 2 else 0
        
        # Find a valid position, possibly shrinking size
        final_loc, final_size, used_original = self.find_valid_position(q_initial_loc, q_size, rotation_z, name)
        
        if used_original:
            print(f"  ✓ {name}: using original position ({final_loc[0]:.2f}, {final_loc[1]:.2f})")
        elif final_size != q_size:
            print(f"  ⚠ {name}: shrunk ({q_size[0]:.2f}x{q_size[1]:.2f}) → ({final_size[0]:.2f}x{final_size[1]:.2f})")
        
        # Create Blender object
        create_object(name, final_loc, final_size, rotation, material, collection, shape)
        
        record = {
            'name': name,
            'location': final_loc,
            'size': final_size,
            'rotation': rotation
        }
        # Furniture is both recorded and participates in later collision checks
        self.placed_objects.append(record)
        self.collision_objects.append(record)
        
        return final_loc
    
    def add_decoration(self, name, location, size, rotation, material, collection, *, collidable_xy=False, shape="box"):
        """Add decoration: do not check collision; overlap is allowed
        
        Args:
            collidable_xy: If True, add to collision_objects even though no collision search is performed, blocking later objects
            shape: "box" or "cylinder"
        """
        # Decorations use fidelity-preserving size quantization by default to avoid visually inflating thin objects and causing intersections
        q_loc = quantize_vec3(location)
        q_size = quantize_size_decoration(size)
        
        create_object(name, q_loc, q_size, rotation, material, collection, shape)
        
        record = {'name': name, 'location': q_loc, 'size': q_size, 'rotation': rotation}
        self.placed_objects.append(record)
        if collidable_xy:
            self.collision_objects.append(record)
        
        flag = "decoration (collider)" if collidable_xy else "decoration"
        print(f"  {name}: {flag}, position ({q_loc[0]:.2f}, {q_loc[1]:.2f})")

    def add_wall_mounted_decoration(self, name, location, size, rotation, material, collection, parent_wall_rec, *, collidable_xy=False):
        """Add wall-mounted decoration (mounted_on):
        Key point: do not round-grid-quantize the position along the wall normal, or it may be pushed into the wall.

        - Still quantize the tangent axis to keep overall alignment
        - Use fidelity-preserving decoration size quantization to avoid thickening thin objects
        """
        if not parent_wall_rec:
            # Fallback: handle as a normal decoration
            return self.add_decoration(
                name, location, size, rotation, material, collection, collidable_xy=collidable_xy
            )

        p_size = parent_wall_rec["size"]
        # Determine the wall thin direction: West/East walls are usually thin on x; North/South walls are usually thin on y
        normal_axis = "x" if p_size[0] < p_size[1] else "y"

        # Position: preserve the normal-axis value; compute_blender_location should already place it on the inner wall surface
        if normal_axis == "x":
            q_loc = (location[0], quantize(location[1]), location[2])
        else:
            q_loc = (quantize(location[0]), location[1], location[2])

        q_size = quantize_size_decoration(size)

        create_object(name, q_loc, q_size, rotation, material, collection, shape="box")

        record = {'name': name, 'location': q_loc, 'size': q_size, 'rotation': rotation}
        self.placed_objects.append(record)
        if collidable_xy:
            self.collision_objects.append(record)

        flag = "wall-mounted decoration (collider)" if collidable_xy else "wall-mounted decoration"
        print(f"  {name}: {flag}, position ({q_loc[0]:.3f}, {q_loc[1]:.3f}) [normal={normal_axis}]")
    
    def add_attached_collidable(self, name, location, size, rotation, material, collection, *, shape="box"):
        """Add an attached collidable object: try the specified position and adjust on collision
        
        Difference from add_furniture:
        - add_furniture: can perform a large-range spiral search
        - add_attached_collidable: only adjusts within a small range to preserve the parent-relative relationship
        
        Args:
            shape: "box" or "cylinder"
        """
        q_size = quantize_size(size)
        q_loc = quantize_vec3(location)
        rotation_z = rotation[2] if len(rotation) > 2 else 0
        
        # Check whether the original position collides
        collision, colliding = self.check_collision_with_placed(q_loc, q_size, rotation_z)
        
        if not collision:
            bbox = get_bbox_2d(q_loc, q_size, rotation_z)
            if self.is_within_scene(bbox):
                final_loc, final_size = q_loc, q_size
                print(f"  ✓ {name}: attached position has no collision ({q_loc[0]:.2f}, {q_loc[1]:.2f})")
            else:
                print(f"  ⚠ {name}: attached position is outside scene bounds")
                final_loc, final_size = q_loc, q_size
        else:
            print(f"  ⚠ {name}: attached position collides with {colliding}; trying to adjust...")
            
            # Try small-range movement, up to 0.5 m
            found = False
            for radius_steps in range(1, 6):  # Up to 0.5 m
                radius = radius_steps * GRID_SIZE
                for angle_idx in range(16):
                    angle = 2 * math.pi * angle_idx / 16
                    new_x = quantize(q_loc[0] + radius * math.cos(angle))
                    new_y = quantize(q_loc[1] + radius * math.sin(angle))
                    new_loc = (new_x, new_y, q_loc[2])
                    
                    bbox = get_bbox_2d(new_loc, q_size, rotation_z)
                    if not self.is_within_scene(bbox):
                        continue
                    
                    coll, _ = self.check_collision_with_placed(new_loc, q_size, rotation_z)
                    if not coll:
                        final_loc, final_size = new_loc, q_size
                        print(f"    → Moved to ({new_x:.2f}, {new_y:.2f})")
                        found = True
                        break
                if found:
                    break
            
            if not found:
                # Try shrinking size
                print(f"    Trying to shrink size...")
                for scale in [0.9, 0.8, 0.7, 0.6, 0.5]:
                    new_size = (quantize_ceil(q_size[0] * scale), quantize_ceil(q_size[1] * scale), q_size[2])
                    if new_size[0] < GRID_SIZE or new_size[1] < GRID_SIZE:
                        break
                    
                    # Try the original position first
                    coll, _ = self.check_collision_with_placed(q_loc, new_size, rotation_z)
                    bbox = get_bbox_2d(q_loc, new_size, rotation_z)
                    if not coll and self.is_within_scene(bbox):
                        final_loc, final_size = q_loc, new_size
                        print(f"    → Shrunk to {scale:.0%}: ({new_size[0]:.2f}, {new_size[1]:.2f})")
                        found = True
                        break
                    
                    # Then try small-range movement
                    for radius_steps in range(1, 6):
                        radius = radius_steps * GRID_SIZE
                        for angle_idx in range(16):
                            angle = 2 * math.pi * angle_idx / 16
                            new_x = quantize(q_loc[0] + radius * math.cos(angle))
                            new_y = quantize(q_loc[1] + radius * math.sin(angle))
                            new_loc = (new_x, new_y, q_loc[2])
                            
                            bbox = get_bbox_2d(new_loc, new_size, rotation_z)
                            if not self.is_within_scene(bbox):
                                continue
                            
                            coll, _ = self.check_collision_with_placed(new_loc, new_size, rotation_z)
                            if not coll:
                                final_loc, final_size = new_loc, new_size
                                print(f"    → Shrunk to {scale:.0%} + moved to ({new_x:.2f}, {new_y:.2f})")
                                found = True
                                break
                        if found:
                            break
                    if found:
                        break
            
            if not found:
                print(f"    ✗ Could not resolve collision; using original position")
                final_loc, final_size = q_loc, q_size
        
        # Create object and record it
        create_object(name, final_loc, final_size, rotation, material, collection, shape)
        record = {'name': name, 'location': final_loc, 'size': final_size, 'rotation': rotation, 'shape': shape}
        self.placed_objects.append(record)
        self.collision_objects.append(record)
        
        return final_loc

    def get_record(self, name):
        """Get object information from placed records, used to attach decorations to the parent object final position"""
        for rec in self.placed_objects:
            if rec["name"] == name:
                return rec
        return None

###############################################################################
# TEMPLATE SECTION (for Prompt / LLM)
# -----------------------------------------------------------------------------
# Implement run_layout_engine() in your final Blender script and use this engine:
#
# def run_layout_engine():
#     clear_scene()
#     STAGE5 = {...}  # Stage5 JSON converted to a Python dict, or loaded from a file
#     SCENE_W = STAGE5["scene"]["scene_w"]
#     SCENE_D = STAGE5["scene"]["scene_d"]
#     WALL_H = STAGE5["scene"].get("wall_h", 2.8)
#     WALL_THICKNESS = quantize_ceil(STAGE5["scene"].get("wall_thickness", 0.15))
#
#     engine = IncrementalLayoutEngine(SCENE_W, SCENE_D, WALL_THICKNESS)
#
#     # 1) Fixed structures: Floor (non-collider) + four walls (colliders) + partitions if any
#     # 2) Follow optimization_order/priority_objects: engine.add_furniture(...)
#     #    Each object placement checks collision_objects and uses spiral search for avoidance
#     # 3) Decorations: use engine.get_record(parent) to get the parent object final position,
#     #    child_xy = parent_xy + offset_xy, then call engine.add_decoration(...)
#
# if __name__ == "__main__":
#     run_layout_engine()
# -----------------------------------------------------------------------------
###############################################################################
